### ISSUE TITLE
Add possibility to augment issuers with additional data

### ISSUE THREAD

**Issue by aahlenst** [ynop/pingu#4]

**Comment by aahlenst** [comment]
I think we already have that: https://github.com/ynop/pingu/blob/65ff38f10fdd354a57ba95bf9554fef01670499f/pingu/corpus/assets/issuer.py#L11-L13

Do we need more, @ynop?

**Comment by ynop** [comment]
Yeah, sorry forgot about that. But I thought about predefining some properties that are often used (e.g. gender). So you can access the gender in a consistent way.

This could either be done by just defining default dictionary keys as global variables/enum/whatever.

Or we add predefined attributes (issuer.gender).

What do you think? I would prefer the first option, since it then is clear, when some information is not available.

**Comment by aahlenst** [comment]
I'm not sure which one is the "first option" you mention. 

In my opinion some metadata classes with predefined properties are a good idea. PyCharm can offer them during auto completion. Another upside would be that we can standardize the values being stored (no mixture of `0`, `no`, `N`, `false`, `False`).

**Comment by ynop** [comment]
Good point, so you would create for example a ``SpeakerMetaData`` class which then provides attributes like ``gender`` or just add those attributes directly to the ``Issuer`` class?

**Comment by aahlenst** [comment]
I wouldn't add the metadata directly to the `Issuer`. I see two options:

1.  We introduce classes like `SpeakerMetaData` and link them with `Issuer`.
2. We declare `Issuer` as abstract and introduce specific subclasses of `Issuer` like `Speaker`. `Speaker` contains the properties like `gender`.

What I don't like about (1) is that we'll end up with various unused properties per instance (a music artist won't have `SpeakerMetaData` but `ArtistMetaData`). (2) avoids this. Maybe with some clever class design we can reduce the amount of time when we have to figure out what type of `Issuer` we're dealing with.

**Comment by ynop** [comment]
Ok then we go with subclassing issuer, but i would not declare it abstract, so it can be used as generic Issuer if needed.

**Comment by aahlenst** [comment]
Conclusion of discussion: `Issuer` will remain an ordinary class and two subtypes, `Speaker` and `Artist`, will be introduced.

```
Speaker {
    gender = {m, f}
    age_group = {child, adult}
    spoken_language = "…" (optionally None)
    native_language = "..." (optionally None)
}
```

```
Artist {
    name = "…"
}
```
