### ISSUE TITLE
Replace nose

### ISSUE THREAD

**Issue by aahlenst** [ynop/pingu#9]
[Nose is unmaintained](https://groups.google.com/forum/#!topic/nose-dev/rkofU1WdNNc).  [nose2](https://github.com/nose-devs/nose2), the successor to nose, is in bugfix mode too. To quote their README:

> However, given the current climate, with much more interest accruing around pytest, nose2 is prioritizing bugfixes and maintenance ahead of new feature development.

Therefore I suggest that we replace nose with [pytest](https://github.com/pytest-dev/pytest/) before we have to rewrite even more tests.

@ynop What do you think?

**Comment by ynop** [comment]
Yes, sounds good. As far as i can see, we don't have to rewrite the tests necessarily, since it supports the ``unittest``-based tests.
